# Generated by Django 5.1.7 on 2025-04-02 08:57

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='địa chỉ email')),
                ('username', models.CharField(blank=True, max_length=150, null=True, verbose_name='tên người dùng')),
                ('full_name', models.CharField(max_length=255, verbose_name='họ và tên')),
                ('student_id', models.CharField(blank=True, max_length=20, null=True, verbose_name='mã sinh viên')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='số điện thoại')),
                ('address', models.TextField(blank=True, null=True, verbose_name='địa chỉ')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='ngày sinh')),
                ('gender', models.CharField(choices=[('male', 'Nam'), ('female', 'Nữ'), ('other', 'Khác')], default='male', max_length=10, verbose_name='giới tính')),
                ('id_card_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='số CMND/CCCD')),
                ('email_verified', models.BooleanField(default=False, verbose_name='email đã xác thực')),
                ('university', models.CharField(blank=True, max_length=255, null=True, verbose_name='trường đại học')),
                ('faculty', models.CharField(blank=True, max_length=255, null=True, verbose_name='khoa')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='ảnh đại diện')),
                ('user_type', models.CharField(choices=[('student', 'Sinh viên'), ('staff', 'Nhân viên'), ('admin', 'Quản trị viên')], default='student', max_length=10, verbose_name='loại người dùng')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='ngày tham gia')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='lần đăng nhập cuối')),
                ('is_active', models.BooleanField(default=True, verbose_name='đang hoạt động')),
                ('is_staff', models.BooleanField(default=False, verbose_name='nhân viên')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'người dùng',
                'verbose_name_plural': 'người dùng',
            },
        ),
        migrations.CreateModel(
            name='PasswordReset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=100, unique=True, verbose_name='mã token')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='thời gian tạo')),
                ('expires_at', models.DateTimeField(verbose_name='thời gian hết hạn')),
                ('is_used', models.BooleanField(default=False, verbose_name='đã sử dụng')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_resets', to=settings.AUTH_USER_MODEL, verbose_name='người dùng')),
            ],
            options={
                'verbose_name': 'đặt lại mật khẩu',
                'verbose_name_plural': 'đặt lại mật khẩu',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('parent_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='tên phụ huynh')),
                ('parent_phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='số điện thoại phụ huynh')),
                ('emergency_contact', models.CharField(blank=True, max_length=255, null=True, verbose_name='liên hệ khẩn cấp')),
                ('emergency_phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='số điện thoại khẩn cấp')),
                ('home_town', models.CharField(blank=True, max_length=255, null=True, verbose_name='quê quán')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='giới thiệu bản thân')),
                ('facebook_url', models.URLField(blank=True, null=True, verbose_name='liên kết Facebook')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='thời gian tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='thời gian cập nhật')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='người dùng')),
            ],
            options={
                'verbose_name': 'hồ sơ người dùng',
                'verbose_name_plural': 'hồ sơ người dùng',
            },
        ),
    ]
